export const companies = [
  {
    id: 1,
    name: "Google",
    image: require("../../assets/icons/companies/ms.png"),
  },
  {
    id: 2,
    name: "Apple",
    image: require("../../assets/icons/companies/google.png"),
  },
  {
    id: 3,
    name: "Facebook",
    image: require("../../assets/icons/companies/meta.png"),
  },
  {
    id: 4,
    name: "Amazon",
    image: require("../../assets/icons/companies/amazon.png"),
  },
  {
    id: 5,
    name: "Microsoft",
    image: require("../../assets/icons/companies/slack.png"),
  },
  {
    id: 6,
    name: "Netflix",
    image: require("../../assets/icons/companies/google.png"),
  },
  {
    id: 7,
    name: "Uber",
    image: require("../../assets/icons/companies/amazon.png"),
  },
  {
    id: 8,
    name: "Airbnb",
    image: require("../../assets/icons/companies/meta.png"),
  },
  {
    id: 9,
    name: "Lyft",
    image: require("../../assets/icons/companies/amazon.png"),
  },
  {
    id: 10,
    name: "Snapchat",
    image: require("../../assets/icons/companies/meta.png"),
  },
];

export const jobs = [
  {
    id: 1,
    company: "Google",
    icon: require("../../assets/icons/companies/google.png"),
    location: "Mountain View, CA",
    postedOn: "2 days ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior Android Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
    tags: ["Remote", "Full Time"],
  },
  {
    id: 2,
    company: "Amazon",
    icon: require("../../assets/icons/companies/amazon.png"),
    location: "Cupertino, CA",
    postedOn: "1 day ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior iOS Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
    tags: ["Remote", "Full Time"],
  },
  {
    id: 3,
    company: "Facebook",
    icon: require("../../assets/icons/companies/meta.png"),
    location: "Menlo Park, CA",
    postedOn: "3 days ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior React Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
    tags: ["Remote", "Full Time"],
  },
  {
    id: 4,
    company: "Google",
    icon: require("../../assets/icons/companies/google.png"),
    location: "Mountain View, CA",
    postedOn: "2 days ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior Android Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
    tags: ["Remote", "Full Time"],
  },
  {
    id: 5,
    company: "Amazon",
    icon: require("../../assets/icons/companies/amazon.png"),
    location: "Cupertino, CA",
    postedOn: "1 day ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior iOS Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
    tags: ["Remote", "Full Time"],
  },
  {
    id: 6,
    company: "Facebook",
    icon: require("../../assets/icons/companies/meta.png"),
    location: "Menlo Park, CA",
    postedOn: "3 days ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior React Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
    tags: ["Remote", "Full Time"],
  },
];
export const apprentises = [
  {
    id: 1,
    company: "Google",
    icon: require("../../assets/icons/companies/google.png"),
    location: "Mountain View, CA",
    postedOn: "2 days ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior Android Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
  },
  {
    id: 2,
    company: "Amazon",
    icon: require("../../assets/icons/companies/amazon.png"),
    location: "Cupertino, CA",
    postedOn: "1 day ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior iOS Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
  },
  {
    id: 3,
    company: "Facebook",
    icon: require("../../assets/icons/companies/meta.png"),
    location: "Menlo Park, CA",
    postedOn: "3 days ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior React Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
  },
  {
    id: 4,
    company: "Google",
    icon: require("../../assets/icons/companies/google.png"),
    location: "Mountain View, CA",
    postedOn: "2 days ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior Android Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
  },
  {
    id: 5,
    company: "Amazon",
    icon: require("../../assets/icons/companies/amazon.png"),
    location: "Cupertino, CA",
    postedOn: "1 day ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior iOS Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
  },
  {
    id: 6,
    company: "Facebook",
    icon: require("../../assets/icons/companies/meta.png"),
    location: "Menlo Park, CA",
    postedOn: "3 days ago",
    responsiblities: [
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Work on bug fixing and improving application performance.",
      "Continuously discover, evaluate, and implement new technologies to maximize development efficiency.",
    ],
    qualifications: [
      "BS/MS degree in Computer Science, Engineering or a related subject.",
      "Proven software development experience and Android skills development.",
      "Proven working experience in Android app development and.",
      "Have published at least one original Android app.",
      "Experience with Android SDK.",
      "Experience working with remote data via REST and JSON.",
      "Experience with third-party libraries and APIs.",
      "Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.",
      "Solid understanding of the full mobile development life cycle.",
    ],
    jobTitle: "Senior React Developer",
    salary: "$80k - $120k",
    type: "Full Time",
    benefits: [
      "Health Insurance",
      "Paid Time Off",
      "Flexible Work Hours",
      "Professional Development",
    ],
    workMode: "Remote",
    timing: "Flexible",
    howToApply: "Send your resume by clicking on the apply now button",
  },
];
